spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  profiles:
    include: oauth
  datasource:
    url: jdbc:mysql://localhost:3306/dev?characterEncoding=UTF-8&serverTimezone=UTC
    username: dev

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true